version: "3.3"

services:
  mysql_server:
    restart: unless-stopped
    image: mysql:latest
    environment: 
      -MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      -MYSQL_USER: 'game'
      -MYSQL_DATABASE: 'mygame'
      -MYSQL_PASSWORD: 'mynewpassword'
    ports:
      -  $DB_LOCAL_PORT:$DB_DOCKER_PORT
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/mysql


  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - mysql_server
    env_file:
      - ./.env
    environment: 
      - DB_URL=$DB_URL
    stdin_open: true
    tty: true

volumes:
  db: